// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeSystemWithAI(arg1) {
  return window['go']['main']['App']['AnalyzeSystemWithAI'](arg1);
}

export function ChatWithAI(arg1) {
  return window['go']['main']['App']['ChatWithAI'](arg1);
}

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetSystemStats() {
  return window['go']['main']['App']['GetSystemStats']();
}

export function Maximize() {
  return window['go']['main']['App']['Maximize']();
}

export function Minimize() {
  return window['go']['main']['App']['Minimize']();
}
