// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzeSystemWithAI(arg1:main.CloudAIRequest):Promise<main.CloudAIResult>;

export function ChatWithAI(arg1:main.CloudAIChatRequest):Promise<main.CloudAIChatResult>;

export function Close():Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetSystemStats():Promise<main.SystemStats>;

export function Maximize():Promise<void>;

export function Minimize():Promise<void>;
